[APPAI-1434] Initial changes for introducing internal API for ingestion
fabric8-analytics/fabric8-analytics-jobs pull request #388
Opened 2020-08-25 06:25 UTC by jparsai

2020-08-26 07:14 UTC, prashbnair requested changes

2020-08-26 07:14 UTC, prashbnair commented on f8a-jobs.py
> +from flask import redirect, jsonify, request
@jparsai A few suggestions, as we are using connexion can you create the api spec and the allow connexion to handle the request handling from the api spec. 
https://engineering.zalando.com/posts/2016/12/crafting-effective-microservices-in-python.html

Also can split the api handling and the calling of the server flow into different files. Can you also put this into a folder like f8a_jobs instead of keeping it in the root folder.

2020-09-02 08:53 UTC, jparsai commented
PTAL on API spec here:
https://app.swaggerhub.com/apis/jparsai/Jobs_API/0.1

2020-09-07 11:50 UTC, prashbnair commented on f8a-jobs.py
> +init_celery(result_backend=False)
can you add a new endpoint named ingestion instead of using api/vi

2020-09-07 12:16 UTC, prashbnair requested changes

2020-09-09 13:33 UTC, jparsai commented on f8a-jobs.py
>  init_selinon()
Introduced new API end point 'ingestion'. In existing YAML base path is set on top and it gets added by to all paths, to have two paths in same YAML, 'api/v1' had to be added in all existing end points along with other modifications for ingestion API.
To avoid all this I have introduced a new YAML, where all the API for ingestion can be added and it will be independent of existing YAML and easy to clean old YAML in future as we have planned.

2020-09-09 13:34 UTC, jparsai commented on f8a_jobs/swagger.yaml
> +  '/ingest-epv':
Updated the API spec.

2020-09-14 09:38 UTC, prashbnair requested changes

2020-09-14 09:38 UTC, prashbnair commented on f8a_jobs/graph_ingestion.py
> +    if not defaults.DISABLE_AUTHENTICATION:
Can you make the authorisation check an annotation. You can take look at the api-server code for this.

2020-09-14 09:38 UTC, prashbnair commented on f8a_jobs/graph_ingestion.py
> +                        logger.info('Incorrect data sent for {}: {}'.format(eco, items))
Can you make this logger.error

2020-09-14 09:38 UTC, prashbnair commented on f8a_jobs/graph_ingestion.py
> +                        if dispacher_ids:
You should wait till all the packages are analysed in the error scenario before sending back the result.

2020-09-14 09:38 UTC, prashbnair commented on f8a_jobs/swagger_ingestion.yaml
> +openapi: 3.0.1
can you call this api_spec.yaml

2020-09-14 09:38 UTC, prashbnair commented on f8a_jobs/swagger_ingestion.yaml
> +  '/ingestions/ingest-epv':
Path should be ingestion/epv. You already have ingestions in the path so no need for ingest again.

2020-09-14 14:53 UTC, jparsai commented on f8a_jobs/graph_ingestion.py
> +                        if dispacher_ids:
Modified the response structure now.
If In any case one of the EPV has wrong details it will not stop entire process but will continue for rest of the EPVs and add failed EPV details into response.
Same way if any unsupported ecosystem is given by user it will add error message for it and  run for other ecosystems, instead of breaking it for all ecosystems.
PTAL on API spec.
https://app.swaggerhub.com/apis/jparsai/Jobs_API/0.1

2020-09-15 11:36 UTC, prashbnair requested changes

2020-09-15 11:36 UTC, prashbnair commented on f8a_jobs/api_spec.yaml
> +            schema:
Can you define the request schema?

2020-09-15 11:36 UTC, prashbnair commented on f8a_jobs/api_spec.yaml
> +            application/json:
The response schema should be similar to the request schema. It should have an ecosystem with an array of package , version and dispatcher id. For package which were incorrect you can add a message without a dispatcher id.

2020-09-15 11:36 UTC, prashbnair commented on f8a_jobs/graph_ingestion.py
> +    """Handle implementation of API for triggering ingestion flow.
Please add a test case for this method.

2020-09-17 07:38 UTC, jparsai commented on f8a_jobs/api_spec.yaml
> +            schema:
I have tried to define schema earlier and checked once again, but it is very tricky to do for request and response, because the request/response JSON key combination and order is not fixed, user can request ingestion for all 3 ecosystems or any one of the ecosystems or any pair of 2 ecosystems, it means we have (3x3) + (2x2) + 1 possible combinations as of now and after golang ingestion available, combinations will increase. Defining schema when key combination is not fixed is very difficult.
In the code level all of the validations are done, this will not create any issue in ingestion.
@prashbnair @yzainee Please suggest me a way to achieve this.

2020-09-18 06:32 UTC, prashbnair commented on f8a_jobs/api_spec.yaml
> +            schema:
If you do not have a schema, how can you parse the request. It seems to me that it is an array and the size of the array varies, is that correct?

2020-09-18 07:29 UTC, jparsai commented on f8a_jobs/api_spec.yaml
> +            schema:
Yes, it is an JSON of Array of JSON
```
{
'pypi': [
              {<first pkg details>}, 
              {<second pkg details>}
]
'maven': [
                 {<first pkg details>}, 
                 {<second pkg details>}
]
}
```
The keys in JSON will change based on ecosystem combination we get, it could be any combination of 3/2/1 ecosystems.
The problem I am having is in API spec to define a schema. I could not find a way to write schema which can validate such random combinations of keys.
In code it can be handled with a loop which checks the key is one of the supported ecosystems or not, I could not find logic in swagger to do similar validation.

2020-09-18 09:00 UTC, prashbnair commented on f8a_jobs/api_spec.yaml
> +            schema:
So can it be 
       ingest_details:
          type: array
          items:
            type: object
            properties:
                ecosystem:
                  type: string
                packages:
                  type: array
                  items:
                      type:object
                      properties:
                          package:
                              type:string
                         version:
                               type:string

2020-09-22 06:59 UTC, prashbnair commented on f8a_jobs/api_spec.yaml
> +      properties:
Doesnt this also need to contain the error message field?

2020-09-22 07:01 UTC, prashbnair commented on f8a_jobs/graph_ingestion.py
> +        input_data = epv_details.get('body', {})
Does the request have a body field?

2020-09-22 07:02 UTC, prashbnair reviewed
Please take a look at the comments

2020-09-22 08:24 UTC, jparsai commented on f8a_jobs/api_spec.yaml
> +      properties:
Sorry, in hurry to finish it, I forgot about error message for incorrect package details. Updated now.

2020-09-22 08:24 UTC, jparsai commented on f8a_jobs/graph_ingestion.py
> +        input_data = epv_details.get('body', {})
No, in request "body" field it is not sent. Please refer to example and its usage in reports.

```
curl --location --request POST 'http://bayesian-jobs-code-ready-development-analytics.apps.ocp.lab.psi.redhat.com/ingestions/epv' \
--header 'auth-token: my-token' \
--header 'Content-Type: application/json' \
--header 'Cookie: e60d3c0af7e0240985026f005511b7fd=f7bbece9a0789fadc11d3bf4093492ec' \
--data-raw '{
"npm": [{
    "package": "esiglobal-components",
        "version": "1.1.6"
    }]}'
```
https://github.com/fabric8-analytics/f8a-stacks-report/blob/338da476b51ab02994266978e7bdcd6888b100cb/f8a_report/helpers/ingestion_helper.py#L28

Swagger is adding it by default in "body", it can be changed using `in:header/query etc`. its name can also be changed using `- name: same-name`.

2020-09-24 02:57 UTC, prashbnair approved these changes

2020-09-30 06:30 UTC, yzainee requested changes

2020-09-30 06:30 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +                                "force": True,
instead of hardcoding these values, we can have an option to either send these values as params.
force and force_graph_sync

2020-09-30 06:30 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +                                "force": True,
If not sent, then by default you can use the values as mentioned here

2020-09-30 06:30 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
Not sure if having all deps in a single call is a good idea. Reason is, if the numbers are high, the processing will take more than 30 secs and the api call will show timeout error. I feel, eco should be passed as a param and only the list of deps for the corresponding eco to be passed along
@prashbnair

2020-09-30 06:54 UTC, jparsai commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
It can be done, but in that case we will have to change in reports. This was raised by Dharmendra/Prashant as well in discussions. The schema change was also requested, but as per the reports PR review, it was decided that all the data will be sent to API as it is and API should do all the things, so I did not do it.
If we are Okay with writing logic in reports to send data by ecosystem and change schema as well, then all the concerns will be addressed.

2020-09-30 07:41 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
your response will timeout. It wont be able to handle so many deps in a single request

2020-09-30 07:43 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
Also, the upstream monitoring runs at its own will and will calling the ingestion APIs respectively. There is no need or a usecase where we need to support multiple ecosystem ingestion to start at the same time. This i feel is an overdo of logic.

2020-09-30 09:00 UTC, jparsai commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
Yes, that is correct, with huge list of packages it will time out, I can change it in API and make required changes in reports PR as well, just want clear that at present also ecosystems are optional in this API, if 1 or 2 ecosystems are sent in request data, it will still work.
@prashbnair Please share your comments, as we are at the end of the Sprint I will have to start it today only.

2020-09-30 09:54 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
even if you keep it as it is, you will anyway have to change in the report to prevent timeout (if any). if this is your sprint task and want to take this up later, i am fine with that as well. But make a note of it and rectify it or else you will end up with several timeouts

2020-09-30 11:27 UTC, prashbnair commented on f8a_jobs/graph_ingestion.py
> +                                "force": True,
+1

2020-09-30 11:36 UTC, prashbnair commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
what is the number of packages we are looking at 500? It should work because run_server_flow is async. This is just like iterating a for loop.

2020-09-30 11:42 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +    'eco1': [{"package": "p1", "version": "v1"},{"package": "p2", "version": "v2"}],
normal ingestion, the numbers are much higher than 500. Its in thousands. however, for supporting via report, the number might not be as high as in ingestion. 
On the async part, yes the method is async, but it will take some fraction/seconds to create the json, add it to the queue and get the id and then the next. if the numbers are more then this might take more than 30 seconds which will in turn throw gateway timeout to the caller function

2020-10-03 05:26 UTC, prashbnair approved these changes

2020-10-05 09:01 UTC, yzainee approved these changes

2020-10-05 09:02 UTC, merged