fix: auth free ingestion API for Internal use.
fabric8-analytics/fabric8-analytics-jobs pull request #393
Opened 2021-01-15 08:07 UTC by jparsai

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

2021-01-15 09:28 UTC, yzainee requested changes

2021-01-15 09:28 UTC, yzainee commented on openshift/template.yaml
> +            value: "0"
please keep it true / false

2021-01-15 09:28 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +        source = input_data.get('source', '')
for all non internal traffic, the source will be 'api' ?

2021-01-15 09:41 UTC, jparsai commented on f8a_jobs/graph_ingestion.py
> +        source = input_data.get('source', '')
For calls made by Utils (i.e API Server and Backbone) source will be "api" and for other components like Github refresh/Reports/Monitors we will have different name. 
It will help us to identify if call is made by SA/CA and we can check for unknown flow flag, otherwise if we give DISABLE_UNKNOWN_PACKAGE_FLOW = True in env variable, it will skip requests from other components as well.
and if we need any validation based on component we can use this parameter in future.

2021-01-15 09:41 UTC, yzainee commented on f8a_jobs/graph_ingestion.py
> +        if source in ['api'] and _DISABLE_UNKNOWN_PACKAGE_FLOW:
i dont understand this condition

2021-01-15 09:50 UTC, jparsai commented on f8a_jobs/graph_ingestion.py
> +        if source in ['api'] and _DISABLE_UNKNOWN_PACKAGE_FLOW:
As we have removed env variable "DISABLE_UNKNOWN_PACKAGE_FLOW" from API Server and backbone it is defined in Jobs repo.
Now if we set it to True in Jobs i.e unknown package ingestion is not allowed then and if we depend on its value only then it will satisfy the condition for all the request and requests will be rejected for all the consumers.
We need  to check this condition only for the requests coming from SA and CA, for this new parameter "source" will be used.

2021-01-15 14:18 UTC, yzainee approved these changes
LGTM

2021-01-18 06:39 UTC, arajkumar requested changes

2021-01-18 06:39 UTC, arajkumar commented on openshift/template.yaml
> +    path: /ingestions
You need to do the same in app-interface Route definition for jobs. Route will be ignored by saas-herder.

2021-01-18 06:39 UTC, arajkumar commented on openshift/template.yaml
> +            value: "False"
Can this be modified to following yaml boolean format?
https://yaml.org/type/bool.html

2021-01-18 06:39 UTC, arajkumar commented on f8a_jobs/graph_ingestion.py
> +        if source in ['api'] and _DISABLE_UNKNOWN_PACKAGE_FLOW:
This check should go out of try block.

2021-01-18 07:10 UTC, jparsai commented on openshift/template.yaml
> +            value: "False"
Okay, But will Jenkins build accept it?
I did this way because once it was discussed in e team that it takes only Strings.

2021-01-19 05:17 UTC, jparsai commented on openshift/template.yaml
> +    path: /ingestions
It is done.
App SRE PR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13897

2021-01-19 05:18 UTC, jparsai commented on openshift/template.yaml
> +    path: /ingestions
It is done.
App SRE PR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/13897

2021-01-20 14:23 UTC, arajkumar requested changes

2021-01-20 14:23 UTC, arajkumar commented on f8a_jobs/api_spec.yaml
> +          example: <name_of_consumer>
If you set of sources, then use enum
```suggestion
          type: string
          enum:
             - api
             - worker
          example: <name_of_consumer>
```

2021-01-20 14:23 UTC, arajkumar commented on f8a_jobs/api_spec.yaml
> +          example: <name_of_consumer>
Also you can specify default value

2021-01-20 14:23 UTC, arajkumar commented on f8a_jobs/graph_ingestion.py
> +    else False
nit:
== returns bool value, no need for if .. else
```suggestion
_DISABLE_UNKNOWN_PACKAGE_FLOW = os.environ.get('DISABLE_UNKNOWN_PACKAGE_FLOW', 'False') == 'True' 
```

2021-01-20 14:23 UTC, arajkumar commented on f8a_jobs/graph_ingestion.py
>      else False
_INVOKE_API_WORKERS = os.environ.get('INVOKE_API_WORKERS', 'True') == 'True'

2021-01-20 14:23 UTC, arajkumar commented on f8a_jobs/graph_ingestion.py
> +    if _INVOKE_API_WORKERS:
return early to keep the block simple.
```suggestion
    if not _INVOKE_API_WORKERS:
       logger.debug('API worker is disabled.')
        input_data['error_message'] = 'Unsupported ecosystem.'
        return input_data, 201
```

2021-01-20 14:23 UTC, arajkumar commented on f8a_jobs/api_spec.yaml
>            type: string
Even ecosystem must be enum.

Basically expressing all the constrains in the spec allows the user of the api to understand the behavior by just looking at the spec rather than groking the code.

2021-01-20 14:23 UTC, arajkumar commented on f8a_jobs/graph_ingestion.py
> +            try:
Add exception to the block which would raise exception, not for all.

2021-01-25 05:12 UTC, arajkumar commented on f8a_jobs/api_spec.yaml
> +          enum:
Don't duplicate, use a separate model/type for Ecosystem.
refer https://github.com/fabric8-analytics/f8a-server-backbone/blob/master/src/v2/openapi.yaml#L125

2021-01-25 05:12 UTC, arajkumar commented on f8a_jobs/api_spec.yaml
> +          enum:
Ditto

2021-01-25 05:33 UTC, arajkumar requested changes
few nits

2021-01-25 05:33 UTC, arajkumar commented on f8a_jobs/api_spec.yaml
> +          enum:
Don't duplicate, use a separate model/type for Ecosystem.
refer https://github.com/fabric8-analytics/f8a-server-backbone/blob/master/src/v2/openapi.yaml#L125

2021-01-25 05:33 UTC, arajkumar commented on f8a_jobs/api_spec.yaml
> +          enum:
Ditto

2021-01-25 09:08 UTC, arajkumar approved these changes
lgtm

2021-01-25 09:11 UTC, merged