fix: Add api endpoint for `componentApiFlow`.
fabric8-analytics/fabric8-analytics-jobs pull request #399
Opened 2021-03-15 15:02 UTC by rafiu007

2021-03-15 15:21 UTC, jparsai requested changes

2021-03-15 15:21 UTC, jparsai commented on f8a_jobs/api_spec.yaml
> +  /ingestions/component-bookkeeping:
You need to set headers for external end point like this 
https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/8a49bc50e8eac33b8ccf15623e30e46c504849d2/f8a_jobs/api_spec.yaml#L13

2021-03-15 15:21 UTC, jparsai commented on f8a_jobs/bookkeeping.py
> +_DISABLE_UNKNOWN_PACKAGE_FLOW = os.environ.get('DISABLE_UNKNOWN_PACKAGE_FLOW', 'False') == 'True'
You don't need this and looks like it is not being used anywhere in your API.

2021-03-15 15:21 UTC, jparsai commented on f8a_jobs/bookkeeping.py
> +    return str(dispacher_id.id), 201
If Selinon failed to trigger the flow you wont get dispatcher id and it will throw error, which will show as an issue in Sentry.

2021-03-15 15:23 UTC, jparsai commented
Please share the link to Swagger Hub API spec in description, so it will be easy to understand the request/response body structure.

2021-03-16 09:20 UTC, rafiu007 reviewed
Swagger Hub api spec : https://app.swaggerhub.com/apis/rafiu007/jobs-api/1.0.0#/Ingestion%20Process/f8a_jobs.bookkeeping.trigger_workerflow_internal

2021-03-19 11:04 UTC, jparsai approved these changes

2021-03-22 11:24 UTC, merged