chore: user caching
fabric8-analytics/fabric8-analytics-jobs pull request #411
Opened 2021-07-13 13:07 UTC by jparsai

2021-07-14 11:29 UTC, yzainee requested changes

2021-07-14 11:29 UTC, yzainee commented on f8a_jobs/user_cache.py
> +            user = json.loads(file.read())
Going forward, if we can make sure that we only store the users which are active in the cache, we wont need to read from the file. It will save us a good amount of time. We will just have to check if the file exists or now. We can make this incremental update while we are in the testing phase etc.

2021-07-14 11:29 UTC, yzainee commented on f8a_jobs/user_cache.py
> +    if _ENABLE_USER_CACHING:
if user caching is disabled, we dont even need to call this api. it can be prevented right at the api server level. why do we want to add this here in jobs?

2021-07-14 11:36 UTC, jparsai commented on f8a-jobs.py
> +    user_cache.create_cache()
No It is part of init function which is called when server is started.

2021-07-14 11:36 UTC, jparsai commented on f8a_jobs/user_cache.py
> +            user = json.loads(file.read())
Yes, we can just update the query to `where status == REGISTERED`, rest will be same.

2021-07-14 11:36 UTC, jparsai commented on f8a_jobs/user_cache.py
> +    if _ENABLE_USER_CACHING:
It is added in API server as well, we can remove it from this API implementation, but env variable re required in Jobs API as well so we dont call gemini API and create cache at the time of server startup.

2021-07-14 12:11 UTC, yzainee commented on f8a_jobs/user_cache.py
> +            user = json.loads(file.read())
if its minor, we can change now itself

2021-07-14 12:16 UTC, jparsai commented on f8a_jobs/user_cache.py
> +            user = json.loads(file.read())
Ack

2021-07-14 12:52 UTC, yzainee commented on f8a_jobs/user_cache.py
> +    if _ENABLE_USER_CACHING:
Ack. for that i agree. for the user api lets stop the call from api server itself

2021-07-14 13:00 UTC, jparsai commented on f8a_jobs/user_cache.py
> +    if _ENABLE_USER_CACHING:
Yes, it is being stopped there only for new user registration we are checking here 
https://github.com/jparsai/fabric8-analytics-server/blob/ccf420d54bce689d721024156dfcd131a044c51a/bayesian/utility/user_utils.py#L66

and for user authentication at the time of running API we are checking here.
https://github.com/jparsai/fabric8-analytics-server/blob/ccf420d54bce689d721024156dfcd131a044c51a/bayesian/auth.py#L39

2021-07-15 09:29 UTC, yzainee approved these changes
LGTM

2021-07-15 09:39 UTC, merged